"""12-hour a_box versus eigen optimization comparison with full diagnostics.

Four independent optimization cases start from the exact same
lattice_config.PARAMETERS:

    1. a_box + h_reduction
    2. eigen + h_reduction
    3. a_box + advisor_derivative
    4. eigen + advisor_derivative

For EACH case, at both START and END:

    1. FMA for delta = 0, +/-0.01, +/-0.02, +/-0.03
    2. tracked-Ix invariance map on the same FMA grid and delta
    3. static Ix section at that delta
    4. Ix-contour versus physical-Poincare tracking at that delta

The optimizer receives 12 hours total per case, including CMA and Powell.
Diagnostics are outside that 12-hour search budget.

This branch is based on FANQO 0.3.dev, so invariant construction is invoked
through fq.compute_invariants(), not fq.construct().
"""

from __future__ import annotations

from importlib.util import find_spec
import csv
import json
from pathlib import Path
import time

import numpy as np

import fanqo as fq
from fanqo import api as _api
from fanqo.core.objective_functions import (
    h_reduction,
    reference_fluctuation_index,
)


BASE_CONFIG = Path(__file__).with_name("general_config.py")
RUNTIME_CONFIG = Path(__file__).with_name("_runtime_compare_12h.py")
EXPERIMENT_ROOT = Path(__file__).with_name("optimization_compare_12h")

CONSTRUCTIONS = ("a_box", "eigen")
OBJECTIVES = ("h_reduction", "advisor_derivative")

OBJECTIVE_FUNCTIONS = {
    "h_reduction": h_reduction,
    "advisor_derivative": reference_fluctuation_index,
}

TOTAL_OPTIMIZATION_HOURS = 12.0
QUICK = False

DIAGNOSTIC_DELTAS = (
    0.0,
    -0.01,
    0.01,
    -0.02,
    0.02,
    -0.03,
    0.03,
)


def _delta_label(delta):
    value = float(delta)
    sign = "p" if value >= 0.0 else "m"
    text = f"{abs(value):.3f}".rstrip("0").rstrip(".").replace(".", "p")
    return f"delta_{sign}{text or '0'}"


def _runtime_text(base_text, *, construction, output_root):
    return base_text + f"""

# ---------------------------------------------------------------------------
# Generated by user/run.py
# ---------------------------------------------------------------------------

INVARIANT_CONSTRUCTION = {construction!r}

# Fixed a_box. No a_box calibration/tuning exists in this branch.
A_BOX = A_BOX.copy()

# FANQO hybrid_optimize uses
#
#   total search ~= CMA_TIME * (1 + POWELL_TIME_FRACTION)
#
# so this makes CMA + Powell total 12 hours.
TOTAL_OPTIMIZATION_HOURS = {float(TOTAL_OPTIMIZATION_HOURS)!r}
CMA_TIME = (
    TOTAL_OPTIMIZATION_HOURS * 3600.0
    / (1.0 + float(POWELL_TIME_FRACTION))
)

# This runner performs the multi-delta diagnostics explicitly.
RUN_FMA_START_END = False

OUTPUT_ROOT = Path({str(output_root)!r})
REPORT_FILE = OUTPUT_ROOT / "optimization_report.txt"
FINAL_LATTICE_FILE = OUTPUT_ROOT / "final_lattice.json"
PLOT_ROOT = OUTPUT_ROOT / "slices"
FMA_OUTPUT_DIRECTORY = OUTPUT_ROOT / "_temporary_FMA"
POINCARE_OUTPUT_DIRECTORY = OUTPUT_ROOT / "_temporary_poincare"
FMA_CASE_LABEL = "temporary"
"""


def _override_config(**updates):
    cfg = _api._cfg()
    previous = {}
    for name, value in updates.items():
        previous[name] = getattr(cfg, name)
        setattr(cfg, name, value)
    return previous


def _restore_config(previous):
    cfg = _api._cfg()
    for name, value in previous.items():
        setattr(cfg, name, value)


def _tracking_stats(diag):
    fmap = np.asarray(diag["fmap"], dtype=float)
    ix_data = np.asarray(diag["ix_data"], dtype=float)

    result = {
        "fma_valid": int(len(fmap)),
        "tracking_points": int(len(ix_data)),
    }

    if len(fmap):
        diffusion = fmap[:, 6]
        result.update({
            "fma_median_log_diffusion": float(np.median(diffusion)),
            "fma_best_log_diffusion": float(np.min(diffusion)),
            "fma_worst_log_diffusion": float(np.max(diffusion)),
        })

    valid = (
        (ix_data[:, 10] > 0.5)
        & np.isfinite(ix_data[:, 8])
    )
    result["ix_valid"] = int(np.count_nonzero(valid))

    if np.any(valid):
        drift = ix_data[valid, 8]
        result.update({
            "ix_median_log_drift": float(np.median(drift)),
            "ix_best_log_drift": float(np.min(drift)),
            "ix_worst_log_drift": float(np.max(drift)),
        })

    return result


def _run_stage_diagnostics(*, run_name, stage, output_root):
    """Run all requested physical diagnostics for the active machine/Ix."""
    stage_root = output_root / stage
    stage_root.mkdir(parents=True, exist_ok=True)

    fq.write_invariant_report(
        file_name=stage_root / "invariant_report.txt",
    )

    results = {}

    for delta in DIAGNOSTIC_DELTAS:
        name = _delta_label(delta)
        root = stage_root / name
        fma_root = root / "FMA"
        invariant_root = root / "invariant"
        poincare_root = root / "poincare"
        reports_root = root / "reports"

        for folder in (
            fma_root,
            invariant_root,
            poincare_root,
            reports_root,
        ):
            folder.mkdir(parents=True, exist_ok=True)

        previous = _override_config(
            FMA_DELTA=float(delta),
            POINCARE_DELTA=float(delta),
            SLICE_DELTA_VALUES=(float(delta),),
            FMA_OUTPUT_DIRECTORY=fma_root,
            POINCARE_OUTPUT_DIRECTORY=poincare_root,
            FMA_CASE_LABEL=f"{run_name}__{stage}__{name}",
        )

        try:
            # Static polynomial Ix section at exactly this delta.
            invariant_paths = fq.plot_invariant(
                folder=invariant_root,
                save=True,
                show=False,
            )

            # Physical tracked Poincare points over the Ix contours.
            poincare = fq.plot_invariant_tracking(
                "x",
                delta=float(delta),
                file_name=(
                    poincare_root
                    / f"Ix_contours_vs_Poincare_{name}.png"
                ),
                turns=int(_api._cfg().POINCARE_TURNS),
                save=True,
                show=False,
            )

            # run_fma performs BOTH:
            #   - physical FMA;
            #   - the dense tracked-Ix invariance map.
            diag_stage = f"{stage}_{name}"
            diag = fq.run_fma(
                stage=diag_stage,
                quick=False,
            )

            fq.write_tracking_report(
                diag_stage,
                file_name=reports_root / "tracking_report.txt",
            )

        finally:
            _restore_config(previous)

        results[name] = {
            "delta": float(delta),
            "frequency_plot": str(diag["frequency_plot_path"]),
            "ix_invariance_plot": str(diag["ix_plot_path"]),
            "fma_csv": str(diag["fma_data_path"]),
            "ix_tracking_csv": str(diag["ix_data_path"]),
            "static_invariant_plots": str(invariant_paths),
            "poincare_plot": str(poincare["plot_path"]),
            "poincare_slice_warning": bool(
                poincare["slice_warning"]
            ),
            "max_other_plane_position": float(
                poincare["max_other_plane_position"]
            ),
            "max_other_plane_momentum": float(
                poincare["max_other_plane_momentum"]
            ),
            **_tracking_stats(diag),
        }

    return results


def _case_record(
    *,
    run_name,
    construction,
    objective_name,
    result,
    output_root,
    optimizer_elapsed,
    start_diagnostics,
    end_diagnostics,
):
    return {
        "run": run_name,
        "construction": construction,
        "objective": objective_name,
        "optimizer_budget_hours": float(TOTAL_OPTIMIZATION_HOURS),
        "optimizer_wall_clock_hours": float(
            optimizer_elapsed / 3600.0
        ),
        "initial_objective": float(
            result["start_details"]["objective"]
        ),
        "final_objective": float(
            result["final_details"]["objective"]
        ),
        "final_parameters": {
            name: float(value)
            for name, value in result["final_parameters"].items()
        },
        "output_directory": str(output_root),
        "start_diagnostics": start_diagnostics,
        "end_diagnostics": end_diagnostics,
    }


def _write_summary(records):
    json_path = EXPERIMENT_ROOT / "comparison_summary.json"
    json_path.write_text(
        json.dumps(records, indent=2),
        encoding="utf-8",
    )

    csv_path = EXPERIMENT_ROOT / "comparison_summary.csv"
    rows = []

    for record in records:
        for stage in ("start", "end"):
            diagnostics = record[f"{stage}_diagnostics"]
            for name, diag in diagnostics.items():
                rows.append({
                    "run": record["run"],
                    "construction": record["construction"],
                    "objective": record["objective"],
                    "stage": stage,
                    "delta": diag["delta"],
                    "fma_valid": diag["fma_valid"],
                    "fma_median_log_diffusion":
                        diag.get("fma_median_log_diffusion"),
                    "ix_valid": diag["ix_valid"],
                    "ix_median_log_drift":
                        diag.get("ix_median_log_drift"),
                    "frequency_plot": diag["frequency_plot"],
                    "ix_invariance_plot":
                        diag["ix_invariance_plot"],
                    "poincare_plot": diag["poincare_plot"],
                })

    columns = [
        "run",
        "construction",
        "objective",
        "stage",
        "delta",
        "fma_valid",
        "fma_median_log_diffusion",
        "ix_valid",
        "ix_median_log_drift",
        "frequency_plot",
        "ix_invariance_plot",
        "poincare_plot",
    ]

    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        writer.writerows(rows)


def main():
    if not BASE_CONFIG.is_file():
        raise FileNotFoundError(
            f"Missing {BASE_CONFIG}. Put run.py beside "
            "general_config.py and lattice_config.py."
        )

    if find_spec("at") is None:
        raise ImportError(
            "Accelerator Toolbox is required for the requested "
            "FMA, Ix tracking, and Poincare diagnostics."
        )

    if TOTAL_OPTIMIZATION_HOURS <= 0.0:
        raise ValueError(
            "TOTAL_OPTIMIZATION_HOURS must be positive."
        )

    base_text = BASE_CONFIG.read_text(encoding="utf-8")
    EXPERIMENT_ROOT.mkdir(parents=True, exist_ok=True)

    records = []

    try:
        for objective_name in OBJECTIVES:
            Fobj = OBJECTIVE_FUNCTIONS[objective_name]

            for construction in CONSTRUCTIONS:
                run_name = f"{construction}__{objective_name}"
                output_root = EXPERIMENT_ROOT / run_name
                output_root.mkdir(parents=True, exist_ok=True)

                RUNTIME_CONFIG.write_text(
                    _runtime_text(
                        base_text,
                        construction=construction,
                        output_root=output_root,
                    ),
                    encoding="utf-8",
                )

                # Every case starts from the original lattice parameters.
                fq.load(RUNTIME_CONFIG, force=True)

                # Original 0.3.dev API: build Ix using the method selected by
                # INVARIANT_CONSTRUCTION in the generated config.
                fq.compute_invariants()

                start_diagnostics = _run_stage_diagnostics(
                    run_name=run_name,
                    stage="start",
                    output_root=output_root,
                )

                optimizer_start = time.monotonic()

                # Diagnostics are explicit, so keep the optimizer itself free
                # of its ordinary single-delta start/end FMA calls.
                result = fq.optimize(
                    Fobj,
                    quick=QUICK,
                    run_start_end_fma=False,
                )

                optimizer_elapsed = (
                    time.monotonic() - optimizer_start
                )

                # optimize() already leaves the winning invariant active, but
                # recomputing it explicitly makes the final diagnostic state
                # unambiguous and uses the same API as the start.
                fq.compute_invariants()

                end_diagnostics = _run_stage_diagnostics(
                    run_name=run_name,
                    stage="end",
                    output_root=output_root,
                )

                fq.write_full_report(
                    file_name=(
                        output_root
                        / "full_report_after_end_diagnostics.txt"
                    ),
                )

                records.append(
                    _case_record(
                        run_name=run_name,
                        construction=construction,
                        objective_name=objective_name,
                        result=result,
                        output_root=output_root,
                        optimizer_elapsed=optimizer_elapsed,
                        start_diagnostics=start_diagnostics,
                        end_diagnostics=end_diagnostics,
                    )
                )

                # Save after every completed case.
                _write_summary(records)

    finally:
        if records:
            _write_summary(records)

        if RUNTIME_CONFIG.exists():
            RUNTIME_CONFIG.unlink()


if __name__ == "__main__":
    main()
