"""Four-run invariant-construction optimization experiment.

Every run starts from the same lattice_config.PARAMETERS.

Matrix:
    a_box + h_reduction
    eigen + h_reduction
    a_box + advisor_derivative
    eigen + advisor_derivative

The a_box is fixed.  No a_box calibration or tuning is performed.

Scientific comparison should use the common physical FMA and tracked-Ix
diagnostics written for each run.  Raw objective values are not assumed to be
numerically comparable between a_box and eigen representations.
"""

from __future__ import annotations

from importlib.util import find_spec
import json
from pathlib import Path

import numpy as np

import fanqo as fq
from fanqo.core.objective_functions import (
    h_reduction,
    reference_fluctuation_index,
)


BASE_CONFIG = Path(__file__).with_name("general_config.py")
RUNTIME_CONFIG = Path(__file__).with_name("_runtime_compare.py")
EXPERIMENT_ROOT = Path(__file__).with_name("optimization_compare")

CONSTRUCTIONS = ("a_box", "eigen")
OBJECTIVES = (
    "h_reduction",
    "advisor_derivative",
)

# False uses the full optimizer budget from general_config.py.
QUICK = False

# Start/end FMA + physical Ix tracking is the common external validation.
RUN_FMA = True


OBJECTIVE_FUNCTIONS = {
    "h_reduction": h_reduction,
    "advisor_derivative": reference_fluctuation_index,
}


def _runtime_text(base_text, construction, objective_name, output_root):
    label = f"{construction}__{objective_name}"
    return base_text + f"""

# --- generated by run.py for one comparison experiment ---
INVARIANT_CONSTRUCTION = {construction!r}

# a_box is deliberately fixed in this branch.
OUTPUT_ROOT = Path({str(output_root)!r})
REPORT_FILE = OUTPUT_ROOT / "optimization_report.txt"
FINAL_LATTICE_FILE = OUTPUT_ROOT / "final_lattice.json"
PLOT_ROOT = OUTPUT_ROOT / "slices"
FMA_OUTPUT_DIRECTORY = OUTPUT_ROOT / "FMA"
POINCARE_OUTPUT_DIRECTORY = OUTPUT_ROOT / "poincare"
FMA_CASE_LABEL = {label!r}
RUN_FMA_START_END = {bool(RUN_FMA)!r}
"""


def _tracking_summary(result):
    diag = result.get("fma_end")
    if not diag:
        return {}

    fmap = np.asarray(diag["fmap"], dtype=float)
    ix_data = np.asarray(diag["ix_data"], dtype=float)

    summary = {
        "fma_valid": int(len(fmap)),
        "tracking_points": int(len(ix_data)),
    }

    if len(fmap):
        summary.update({
            "fma_median_log_diffusion": float(np.median(fmap[:, 6])),
            "fma_best_log_diffusion": float(np.min(fmap[:, 6])),
            "fma_worst_log_diffusion": float(np.max(fmap[:, 6])),
        })

    valid = (
        (ix_data[:, 10] > 0.5)
        & np.isfinite(ix_data[:, 8])
    )
    summary["ix_valid"] = int(np.count_nonzero(valid))
    if np.any(valid):
        drift = ix_data[valid, 8]
        summary.update({
            "ix_median_log_drift": float(np.median(drift)),
            "ix_best_log_drift": float(np.min(drift)),
            "ix_worst_log_drift": float(np.max(drift)),
        })

    return summary


def main():
    base_text = BASE_CONFIG.read_text(encoding="utf-8")
    EXPERIMENT_ROOT.mkdir(parents=True, exist_ok=True)

    tracking_available = find_spec("at") is not None
    if RUN_FMA and not tracking_available:
        raise ImportError(
            "RUN_FMA=True requires Accelerator Toolbox."
        )

    records = []

    try:
        for objective_name in OBJECTIVES:
            Fobj = OBJECTIVE_FUNCTIONS[objective_name]

            for construction in CONSTRUCTIONS:
                run_name = f"{construction}__{objective_name}"
                output_root = EXPERIMENT_ROOT / run_name

                RUNTIME_CONFIG.write_text(
                    _runtime_text(
                        base_text,
                        construction,
                        objective_name,
                        output_root,
                    ),
                    encoding="utf-8",
                )

                # load() always rebuilds from lattice_config.PARAMETERS, so all
                # four optimizations start from exactly the same machine.
                fq.load(RUNTIME_CONFIG, force=True)

                result = fq.optimize(
                    Fobj,
                    quick=QUICK,
                    run_start_end_fma=RUN_FMA,
                )

                fq.write_full_report(
                    output_root / "full_report.txt"
                )

                record = {
                    "run": run_name,
                    "construction": construction,
                    "objective": objective_name,
                    "initial_objective": float(
                        result["start_details"]["objective"]
                    ),
                    "final_objective": float(
                        result["final_details"]["objective"]
                    ),
                    "output_directory": str(output_root),
                    "final_parameters": {
                        name: float(value)
                        for name, value in result["final_parameters"].items()
                    },
                    **_tracking_summary(result),
                }
                records.append(record)

        summary_path = EXPERIMENT_ROOT / "comparison_summary.json"
        summary_path.write_text(
            json.dumps(records, indent=2),
            encoding="utf-8",
        )

    finally:
        if RUNTIME_CONFIG.exists():
            RUNTIME_CONFIG.unlink()


if __name__ == "__main__":
    main()
