"""12-hour a_box versus eigen optimization comparison.

Four independent optimization cases are run from the exact same
lattice_config.PARAMETERS:

    1. a_box + h_reduction
    2. eigen + h_reduction
    3. a_box + advisor_derivative
    4. eigen + advisor_derivative

Every case receives the same TOTAL optimizer wall-clock budget.  The budget
includes both CMA-ES and Powell:

    TOTAL = CMA_TIME + POWELL_TIME_FRACTION * CMA_TIME

so CMA_TIME is chosen automatically from TOTAL_OPTIMIZATION_HOURS.

Physical FMA and tracked-Ix diagnostics are run both BEFORE and AFTER each
optimization.  Their runtime is validation overhead and is intentionally not
subtracted from the 12-hour optimizer budget.

A_BOX is fixed.  No a_box tuning/calibration is performed.
"""

from __future__ import annotations

from importlib.util import find_spec
import csv
import json
from pathlib import Path
import time

import numpy as np

import fanqo as fq
from fanqo.core.objective_functions import (
    h_reduction,
    reference_fluctuation_index,
)


# =============================================================================
# EXPERIMENT SETTINGS
# =============================================================================

BASE_CONFIG = Path(__file__).with_name("general_config.py")
RUNTIME_CONFIG = Path(__file__).with_name("_runtime_compare_12h.py")
EXPERIMENT_ROOT = Path(__file__).with_name("optimization_compare_12h")

CONSTRUCTIONS = (
    "a_box",
    "eigen",
)

OBJECTIVES = (
    "h_reduction",
    "advisor_derivative",
)

OBJECTIVE_FUNCTIONS = {
    "h_reduction": h_reduction,
    "advisor_derivative": reference_fluctuation_index,
}

# Equal search budget for EVERY construction/objective case.
TOTAL_OPTIMIZATION_HOURS = 12.0

# FMA + physical Ix tracking before and after each optimization.
RUN_FMA = True

# False = real 12-hour experiments.
# True is only a smoke test; fq.optimize() internally shortens the budget.
QUICK = False


# =============================================================================
# RUNTIME CONFIG
# =============================================================================

def _runtime_text(
    base_text,
    *,
    construction,
    objective_name,
    output_root,
):
    """Generate one isolated FANQO config for a single experiment."""
    label = f"{construction}__{objective_name}"

    # In FANQO:
    #
    #   total search time ~= CMA_TIME + POWELL_TIME_FRACTION*CMA_TIME
    #
    # Therefore solve for CMA_TIME so CMA+Powell receives exactly the same
    # 12-hour budget in every case.
    return base_text + f"""

# ---------------------------------------------------------------------------
# Generated by run.py: {label}
# ---------------------------------------------------------------------------

INVARIANT_CONSTRUCTION = {construction!r}

# Fixed a_box: never tuned in this comparison.
A_BOX = A_BOX.copy()

# Equal TOTAL optimizer budget.
TOTAL_OPTIMIZATION_HOURS = {float(TOTAL_OPTIMIZATION_HOURS)!r}
CMA_TIME = (
    TOTAL_OPTIMIZATION_HOURS * 3600.0
    / (1.0 + float(POWELL_TIME_FRACTION))
)

# Independent outputs for this case.
OUTPUT_ROOT = Path({str(output_root)!r})
REPORT_FILE = OUTPUT_ROOT / "optimization_report.txt"
FINAL_LATTICE_FILE = OUTPUT_ROOT / "final_lattice.json"
PLOT_ROOT = OUTPUT_ROOT / "slices"
FMA_OUTPUT_DIRECTORY = OUTPUT_ROOT / "FMA"
POINCARE_OUTPUT_DIRECTORY = OUTPUT_ROOT / "poincare"

FMA_CASE_LABEL = {label!r}
RUN_FMA_START_END = {bool(RUN_FMA)!r}
"""


# =============================================================================
# SUMMARY HELPERS
# =============================================================================

def _fma_summary(diag, prefix):
    """Extract comparable FMA + Ix-tracking statistics."""
    if not diag:
        return {}

    fmap = np.asarray(diag["fmap"], dtype=float)
    ix_data = np.asarray(diag["ix_data"], dtype=float)

    summary = {
        f"{prefix}_fma_valid": int(len(fmap)),
        f"{prefix}_tracking_points": int(len(ix_data)),
    }

    if len(fmap):
        diffusion = fmap[:, 6]
        summary.update({
            f"{prefix}_fma_median_log_diffusion":
                float(np.median(diffusion)),
            f"{prefix}_fma_best_log_diffusion":
                float(np.min(diffusion)),
            f"{prefix}_fma_worst_log_diffusion":
                float(np.max(diffusion)),
        })

    valid = (
        (ix_data[:, 10] > 0.5)
        & np.isfinite(ix_data[:, 8])
    )
    summary[f"{prefix}_ix_valid"] = int(np.count_nonzero(valid))

    if np.any(valid):
        drift = ix_data[valid, 8]
        summary.update({
            f"{prefix}_ix_median_log_drift":
                float(np.median(drift)),
            f"{prefix}_ix_best_log_drift":
                float(np.min(drift)),
            f"{prefix}_ix_worst_log_drift":
                float(np.max(drift)),
        })

    return summary


def _case_record(
    run_name,
    construction,
    objective_name,
    result,
    output_root,
    elapsed_seconds,
):
    record = {
        "run": run_name,
        "construction": construction,
        "objective": objective_name,
        "optimizer_budget_hours": float(TOTAL_OPTIMIZATION_HOURS),
        "case_wall_clock_hours": float(elapsed_seconds / 3600.0),
        "initial_objective": float(
            result["start_details"]["objective"]
        ),
        "final_objective": float(
            result["final_details"]["objective"]
        ),
        "output_directory": str(output_root),
        "final_parameters": {
            name: float(value)
            for name, value in result["final_parameters"].items()
        },
    }

    record.update(
        _fma_summary(result.get("fma_start"), "start")
    )
    record.update(
        _fma_summary(result.get("fma_end"), "end")
    )
    return record


def _write_summary(records):
    """Write both detailed JSON and a compact CSV comparison table."""
    json_path = EXPERIMENT_ROOT / "comparison_summary.json"
    json_path.write_text(
        json.dumps(records, indent=2),
        encoding="utf-8",
    )

    csv_path = EXPERIMENT_ROOT / "comparison_summary.csv"

    columns = [
        "run",
        "construction",
        "objective",
        "optimizer_budget_hours",
        "case_wall_clock_hours",
        "initial_objective",
        "final_objective",
        "start_fma_valid",
        "start_fma_median_log_diffusion",
        "end_fma_valid",
        "end_fma_median_log_diffusion",
        "start_ix_valid",
        "start_ix_median_log_drift",
        "end_ix_valid",
        "end_ix_median_log_drift",
    ]

    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=columns,
            extrasaction="ignore",
        )
        writer.writeheader()
        writer.writerows(records)


# =============================================================================
# MAIN EXPERIMENT
# =============================================================================

def main():
    base_text = BASE_CONFIG.read_text(encoding="utf-8")
    EXPERIMENT_ROOT.mkdir(parents=True, exist_ok=True)

    if TOTAL_OPTIMIZATION_HOURS <= 0.0:
        raise ValueError(
            "TOTAL_OPTIMIZATION_HOURS must be positive."
        )

    if RUN_FMA and find_spec("at") is None:
        raise ImportError(
            "RUN_FMA=True requires Accelerator Toolbox."
        )

    records = []

    try:
        for objective_name in OBJECTIVES:
            Fobj = OBJECTIVE_FUNCTIONS[objective_name]

            for construction in CONSTRUCTIONS:
                run_name = (
                    f"{construction}__{objective_name}"
                )
                output_root = EXPERIMENT_ROOT / run_name
                output_root.mkdir(parents=True, exist_ok=True)

                RUNTIME_CONFIG.write_text(
                    _runtime_text(
                        base_text,
                        construction=construction,
                        objective_name=objective_name,
                        output_root=output_root,
                    ),
                    encoding="utf-8",
                )

                # Critical fairness condition:
                # fq.load() rebuilds from lattice_config.PARAMETERS.
                # No optimized result from the previous case is reused.
                fq.load(
                    RUNTIME_CONFIG,
                    force=True,
                )

                case_start = time.monotonic()

                # fq.optimize(..., run_start_end_fma=True) does:
                #
                #   initial invariant
                #   -> START FMA + tracked Ix
                #   -> 12-hour CMA/Powell optimization
                #   -> final invariant
                #   -> END FMA + tracked Ix
                #
                result = fq.optimize(
                    Fobj,
                    quick=QUICK,
                    run_start_end_fma=RUN_FMA,
                )

                elapsed = time.monotonic() - case_start

                fq.write_full_report(
                    output_root / "full_report.txt"
                )

                records.append(
                    _case_record(
                        run_name,
                        construction,
                        objective_name,
                        result,
                        output_root,
                        elapsed,
                    )
                )

                # Keep an up-to-date summary after every completed case so a
                # long campaign still preserves all finished results if a
                # later case is interrupted.
                _write_summary(records)

    finally:
        if records:
            _write_summary(records)

        if RUNTIME_CONFIG.exists():
            RUNTIME_CONFIG.unlink()


if __name__ == "__main__":
    main()
