"""Compare constructors using your existing general_config.py and FANQO plots.

Run: python run_structured_comparison.py
No lattice optimization. No replacement lattice, tracking metric or grid.
"""
from pathlib import Path
import argparse
import csv
import time
import tempfile
import numpy as np
import fanqo as fq
from fanqo import api as _api

CONSTRUCTIONS = ('a_box', 'eigen', 'a_box_coupled_fixed',
                 'a_box_coupled_regularized', 'graded_coupled', 'canonical_graded')
DIAGNOSTIC_DELTAS = (0., -.01, .01, -.02, .02, -.03, .03)

def _delta_label(delta):
    value = float(delta)
    sign = "p" if value >= 0.0 else "m"
    text = f"{abs(value):.3f}".rstrip("0").rstrip(".").replace(".", "p")
    return f"delta_{sign}{text or '0'}"


def _runtime_text(base_text, *, construction, output_root):
    return base_text + f"""

# ---------------------------------------------------------------------------
# Generated by user/run.py
# ---------------------------------------------------------------------------

INVARIANT_CONSTRUCTION = {construction!r}

# Fixed a_box. No a_box calibration/tuning exists in this branch.
A_BOX = A_BOX.copy()

# This runner performs the multi-delta diagnostics explicitly.
RUN_FMA_START_END = False

OUTPUT_ROOT = Path({str(output_root)!r})
REPORT_FILE = OUTPUT_ROOT / "optimization_report.txt"
FINAL_LATTICE_FILE = OUTPUT_ROOT / "final_lattice.json"
PLOT_ROOT = OUTPUT_ROOT / "slices"
FMA_OUTPUT_DIRECTORY = OUTPUT_ROOT / "_temporary_FMA"
POINCARE_OUTPUT_DIRECTORY = OUTPUT_ROOT / "_temporary_poincare"
FMA_CASE_LABEL = "temporary"
"""


def _override_config(**updates):
    cfg = _api._cfg()
    previous = {}
    for name, value in updates.items():
        previous[name] = getattr(cfg, name)
        setattr(cfg, name, value)
    return previous


def _restore_config(previous):
    cfg = _api._cfg()
    for name, value in previous.items():
        setattr(cfg, name, value)


def _tracking_stats(diag):
    fmap = np.asarray(diag["fmap"], dtype=float)
    ix_data = np.asarray(diag["ix_data"], dtype=float)

    result = {
        "fma_valid": int(len(fmap)),
        "tracking_points": int(len(ix_data)),
    }

    if len(fmap):
        diffusion = fmap[:, 6]
        result.update({
            "fma_median_log_diffusion": float(np.median(diffusion)),
            "fma_best_log_diffusion": float(np.min(diffusion)),
            "fma_worst_log_diffusion": float(np.max(diffusion)),
        })

    valid = (
        (ix_data[:, 10] > 0.5)
        & np.isfinite(ix_data[:, 8])
    )
    result["ix_valid"] = int(np.count_nonzero(valid))

    if np.any(valid):
        drift = ix_data[valid, 8]
        result.update({
            "ix_median_log_drift": float(np.median(drift)),
            "ix_best_log_drift": float(np.min(drift)),
            "ix_worst_log_drift": float(np.max(drift)),
        })

    return result


def _run_stage_diagnostics(*, run_name, stage, output_root):
    """Run all requested physical diagnostics for the active machine/Ix."""
    stage_root = output_root / stage
    stage_root.mkdir(parents=True, exist_ok=True)

    fq.write_invariant_report(
        file_name=stage_root / "invariant_report.txt",
    )

    results = {}

    for delta in DIAGNOSTIC_DELTAS:
        name = _delta_label(delta)
        root = stage_root / name
        fma_root = root / "FMA"
        invariant_root = root / "invariant"
        poincare_root = root / "poincare"
        reports_root = root / "reports"

        for folder in (
            fma_root,
            invariant_root,
            poincare_root,
            reports_root,
        ):
            folder.mkdir(parents=True, exist_ok=True)

        previous = _override_config(
            FMA_DELTA=float(delta),
            POINCARE_DELTA=float(delta),
            SLICE_DELTA_VALUES=(float(delta),),
            FMA_OUTPUT_DIRECTORY=fma_root,
            POINCARE_OUTPUT_DIRECTORY=poincare_root,
            FMA_CASE_LABEL=f"{run_name}__{stage}__{name}",
        )

        try:
            # Static polynomial Ix section at exactly this delta.
            invariant_paths = fq.plot_invariant(
                folder=invariant_root,
                save=True,
                show=False,
            )

            # Physical tracked Poincare points over the Ix contours.
            poincare = fq.plot_invariant_tracking(
                "x",
                delta=float(delta),
                file_name=(
                    poincare_root
                    / f"Ix_contours_vs_Poincare_{name}.png"
                ),
                turns=int(_api._cfg().POINCARE_TURNS),
                save=True,
                show=False,
            )

            # run_fma performs BOTH:
            #   - physical FMA;
            #   - the dense tracked-Ix invariance map.
            diag_stage = f"{stage}_{name}"
            diag = fq.run_fma(
                stage=diag_stage,
                quick=False,
            )

            fq.write_tracking_report(
                diag_stage,
                file_name=reports_root / "tracking_report.txt",
            )

        finally:
            _restore_config(previous)

        results[name] = {
            "delta": float(delta),
            "frequency_plot": str(diag["frequency_plot_path"]),
            "ix_invariance_plot": str(diag["ix_plot_path"]),
            "fma_csv": str(diag["fma_data_path"]),
            "ix_tracking_csv": str(diag["ix_data_path"]),
            "static_invariant_plots": str(invariant_paths),
            "poincare_plot": str(poincare["plot_path"]),
            "poincare_slice_warning": bool(
                poincare["slice_warning"]
            ),
            "max_other_plane_position": float(
                poincare["max_other_plane_position"]
            ),
            "max_other_plane_momentum": float(
                poincare["max_other_plane_momentum"]
            ),
            **_tracking_stats(diag),
        }

    return results


def main():
    global DIAGNOSTIC_DELTAS
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--config', default=str(Path(__file__).with_name('general_config.py')))
    parser.add_argument('--methods', nargs='+', default=CONSTRUCTIONS)
    parser.add_argument('--deltas', type=float, nargs='+', default=DIAGNOSTIC_DELTAS)
    parser.add_argument('--timing-only', action='store_true')
    parser.add_argument('--output', default='constructor_comparison')
    args = parser.parse_args()
    DIAGNOSTIC_DELTAS = tuple(args.deltas)
    config = Path(args.config).resolve()
    base_text = config.read_text(encoding='utf-8')
    output = Path(args.output).resolve()
    output.mkdir(parents=True, exist_ok=True)
    # Keep relative lattice paths relative to the user's original config.
    with tempfile.NamedTemporaryFile(mode='w', suffix='.py', prefix='_constructor_',
                                     dir=config.parent, delete=False) as handle:
        runtime = Path(handle.name)
    rows = []
    try:
        for method in args.methods:
            root = output / method
            root.mkdir(parents=True, exist_ok=True)
            runtime.write_text(_runtime_text(base_text, construction=method, output_root=root), encoding='utf-8')
            print(f'Constructing {method} ...', flush=True)
            fq.load(runtime, force=True)
            start = time.perf_counter()
            fq.compute_invariants()
            elapsed = time.perf_counter()-start
            rows.append(dict(method=method, compute_invariants_seconds=elapsed))
            with (output/'construction_times.csv').open('w', newline='') as f:
                writer = csv.DictWriter(f, fieldnames=list(rows[0]))
                writer.writeheader(); writer.writerows(rows)
            print(f'  compute_invariants: {elapsed:.6f} s (includes map preparation)', flush=True)
            if not args.timing_only:
                _run_stage_diagnostics(run_name=method, stage='comparison', output_root=root)
    finally:
        runtime.unlink(missing_ok=True)

if __name__ == '__main__':
    main()
